'use client';
import { useEffect, useRef, useState } from 'react';
import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { RotateCcw, Plus, Minus, Move, MousePointer2, ArrowUpRight, Brain, ChevronRight } from 'lucide-react';

const parts = [
 {name:'Dendrites',color:'#e6a875',verb:'Receive',text:'Branching extensions receive most of the neuron’s incoming synaptic signals. Receptors respond to neurotransmitters released by other cells.',whole:'These inputs change the membrane voltage. Their combined effects help determine whether the neuron sends an action potential.',note:'A neuron can receive thousands of inputs across its dendritic tree.'},
 {name:'Cell body',color:'#d78565',verb:'Maintain & integrate',text:'Also called the soma, the cell body contains the nucleus and organelles that keep the neuron alive. It also receives synaptic inputs.',whole:'The soma supports the whole cell and helps integrate signals arriving from dendrites before they influence the axon’s initial segment.',note:'The soma is the neuron’s metabolic center.'},
 {name:'Nucleus',color:'#e6b6da',verb:'Direct cell activity',text:'The nucleus houses DNA. Gene expression provides instructions for making proteins that the neuron needs to function and adapt.',whole:'Those proteins support receptors, ion channels, cell maintenance, and changes involved in learning.',note:'Shown through a translucent soma so you can see its position.'},
 {name:'Axon initial segment',color:'#f4cc73',verb:'Initiate',text:'Just beyond the axon hillock, this specialized region has a high density of voltage-gated ion channels. Action potentials usually begin here when threshold is reached.',whole:'It converts the combined influence of incoming signals into an electrical output that can travel down the axon.',note:'The hillock is the taper from soma to axon; the initial segment follows it.'},
 {name:'Axon',color:'#efb778',verb:'Conduct',text:'The axon carries action potentials away from the cell body toward its terminals. Its membrane regenerates the electrical signal as it travels.',whole:'It links the neuron’s input and integration regions to the cells that will receive its output.',note:'Axon length varies widely between neuron types.'},
 {name:'Myelin sheath',color:'#8bcbbb',verb:'Insulate',text:'Myelin is a fatty, multilayered wrapping made by glial cells around some axons. It reduces current leakage and speeds signal conduction.',whole:'Insulation lets electrical current spread rapidly between gaps, making long-distance communication more efficient.',note:'Oligodendrocytes form CNS myelin; Schwann cells form PNS myelin.'},
 {name:'Nodes of Ranvier',color:'#f1d481',verb:'Regenerate',text:'Nodes are small gaps between myelin segments. Concentrated ion channels regenerate the action potential at these exposed regions.',whole:'In saltatory conduction, current spreads beneath myelin and the action potential is renewed at successive nodes.',note:'The signal does not literally leap through empty space.'},
 {name:'Axon terminals',color:'#b39fe8',verb:'Transmit',text:'Terminal branches form connections with target cells. At chemical synapses, an arriving action potential triggers calcium entry and neurotransmitter release.',whole:'Neurotransmitters cross the synaptic cleft and bind receptors on the next cell, influencing its activity.',note:'A synapse includes the terminal, the cleft, and the receiving cell’s specialization.'},
];
function Neuron({selected,onSelect,api}:{selected:number;onSelect:(n:number)=>void;api:React.MutableRefObject<{reset:()=>void;zoom:(n:number)=>void}|null>}) {
 const host=useRef<HTMLDivElement>(null);const selection=useRef(selected);selection.current=selected; const [error,setError]=useState(false);
 useEffect(()=>{if(!host.current)return;const el=host.current;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});}catch{setError(true);return;}
 renderer.setPixelRatio(Math.min(devicePixelRatio,2));el.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Rotatable 3D neuron. Drag to rotate, scroll to zoom, or select a structure.');
 const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(38,1,.1,100);camera.position.set(0,0,23);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=12;controls.maxDistance=36;controls.target.set(.3,0,0);
 scene.add(new THREE.HemisphereLight(0xd9e8ff,0x403e52,2.5));const light=new THREE.DirectionalLight(0xffe3c4,3);light.position.set(-3,6,10);scene.add(light);const rim=new THREE.DirectionalLight(0x92cfe8,2);rim.position.set(3,-2,-5);scene.add(rim);
 const group=new THREE.Group();scene.add(group);group.rotation.z=.12;const meshes:THREE.Mesh[]=[];
 function material(i:number){return new THREE.MeshStandardMaterial({color:parts[i].color,roughness:.37,metalness:.12,transparent:i===1,opacity:i===1?.65:1});}
 function ball(p:number[],r:number,i:number,scale=[1,1,1]){const m=new THREE.Mesh(new THREE.SphereGeometry(r,32,24),material(i));m.position.set(...p as [number,number,number]);m.scale.set(...scale as [number,number,number]);m.userData.part=i;group.add(m);meshes.push(m);return m;}
 function tube(points:number[][],radius:number,i:number){const curve=new THREE.CatmullRomCurve3(points.map(p=>new THREE.Vector3(...p as [number,number,number])));const m=new THREE.Mesh(new THREE.TubeGeometry(curve,32,radius,12,false),material(i));m.userData.part=i;group.add(m);meshes.push(m);return m;}
 ball([-3,0,0],1.12,1,[1.12,1,.86]);ball([-3,.04,.55],.43,2);
 const angles=[.8,1.45,2.05,2.65,3.3,3.9,4.55,5.05];angles.forEach((a,j)=>{const origin=[-3+Math.cos(a)*.65,Math.sin(a)*.65,0];const mid=[-3+Math.cos(a)*1.7,Math.sin(a)*1.7,Math.sin(j*2)*.45];const tip=[-3+Math.cos(a)*3,Math.sin(a)*3,Math.sin(j)*.8];tube([origin,mid,tip],.105,0);for(let k=0;k<2;k++){const b=a+(k===0?-.4:.4);const end=[tip[0]+Math.cos(b)*.95,tip[1]+Math.sin(b)*.95,tip[2]+(k-.5)*.6];tube([mid,tip,end],.047,0);const twig=[end[0]+Math.cos(b+.45)*.45,end[1]+Math.sin(b+.45)*.45,end[2]+.2];tube([end,twig],.024,0);}});
 tube([[-2.2,-.15,0],[-1.65,-.35,0],[-1.2,-.38,0]],.2,3);tube([[-1.2,-.38,0],[1,-.5,.15],[3,-.65,0],[5,-.9,.1]],.1,4);
 for(let j=0;j<5;j++){const x=-.9+j*1.12;const y=-.4-(x+.9)*.09;tube([[x,y,0],[x+.4,y-.02,.06],[x+.86,y-.075,.02]],.28,5);if(j<4)ball([x+.98,y-.085,.02],.135,6,[.8,1,1]);}
 for(let j=0;j<5;j++){const y=(j-2)*.62-1;const end=[6.3+Math.cos(j)*.28,y,Math.sin(j)*.65];tube([[4.7,-.86,.05],[5.4,y*.8,0],end],.065,7);ball(end,.16,7);}
 const ray=new THREE.Raycaster();const pointer=new THREE.Vector2();let down=[0,0];const start=(e:PointerEvent)=>{down=[e.clientX,e.clientY];};const pick=(e:PointerEvent)=>{if(Math.hypot(e.clientX-down[0],e.clientY-down[1])>6)return;const b=el.getBoundingClientRect();pointer.set((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1);ray.setFromCamera(pointer,camera);const hits=ray.intersectObjects(meshes);if(hits.length)onSelect(hits[0].object.userData.part);};renderer.domElement.addEventListener('pointerdown',start);renderer.domElement.addEventListener('pointerup',pick);
 api.current={reset:()=>{camera.position.set(0,0,23);controls.target.set(.3,0,0);controls.update();},zoom:(n)=>{camera.position.sub(controls.target).multiplyScalar(n).clampLength(12,36).add(controls.target);controls.update();}};
 const resize=()=>{const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();};const observer=new ResizeObserver(resize);observer.observe(el);resize();let frame=0;const animate=()=>{frame=requestAnimationFrame(animate);controls.update();meshes.forEach(m=>{const mat=m.material as THREE.MeshStandardMaterial;mat.emissive.set(m.userData.part===selection.current?parts[selection.current].color:'#000000');mat.emissiveIntensity=m.userData.part===selection.current?.23:0;});renderer.render(scene,camera);};animate();
 return()=>{cancelAnimationFrame(frame);observer.disconnect();controls.dispose();meshes.forEach(m=>{m.geometry.dispose();(m.material as THREE.Material).dispose();});renderer.dispose();renderer.domElement.remove();api.current=null;};
 },[onSelect,api]);
 return <div className="canvas" ref={host}>{error&&<p className="render-error">3D rendering is unavailable in this browser. Try a browser with WebGL enabled. You can still explore every structure using the list below.</p>}</div>;
}
export default function Home(){const [selected,setSelected]=useState(0);const api=useRef<{reset:()=>void;zoom:(n:number)=>void}|null>(null);const p=parts[selected];return <main>
 <header><a className="brand" href="/"><span className="brandmark"><Brain size={23}/></span>NEURON<span className="brand-light">/ explored</span></a><span className="course">PSYCHOLOGY · INTERACTIVE ATLAS</span><span className="edition">01 <span>/ The neuron</span></span></header>
 <section className="intro"><div><div className="eyebrow">THE BUILDING BLOCKS OF BEHAVIOR</div><h1>A closer look at the neuron.</h1><p>Explore its structure. Understand how it communicates.</p></div><div className="model-type"><span/> Multipolar neuron <small>3D study model</small></div></section>
 <section className="workspace"><div className="viewer"><div className="viewer-top"><span className="tiny">STRUCTURE EXPLORER</span><span className="live"><i/> INTERACTIVE 3D</span></div><Neuron selected={selected} onSelect={setSelected} api={api}/><div className="selection-badge"><span style={{background:p.color}}/> {p.name}<span className="selected-word">selected</span></div><div className="viewer-bottom"><span><Move size={15}/> Drag to rotate <span className="dot">·</span> Scroll to zoom</span><div className="view-controls"><button aria-label="Zoom in" onClick={()=>api.current?.zoom(.85)}><Plus size={18}/></button><button aria-label="Zoom out" onClick={()=>api.current?.zoom(1.18)}><Minus size={18}/></button><button aria-label="Reset model view" onClick={()=>api.current?.reset()}><RotateCcw size={17}/></button></div></div></div>
 <aside className="detail" aria-live="polite" aria-atomic="true"><div className="detail-top"><span className="tiny">ANATOMY NOTE</span><span className="part-number">0{selected+1} / 08</span></div><div className="part-icon" style={{color:p.color,borderColor:p.color+'55',background:p.color+'12'}}><Brain size={29}/></div><span className="function-label" style={{color:p.color}}>{p.verb}</span><h2>{p.name}</h2><p>{p.text}</p><div className="relation"><h3>In the whole neuron</h3><p>{p.whole}</p></div><div className="remember"><span>KEEP IN MIND</span><p>{p.note}</p></div><button className="next" onClick={()=>setSelected((selected+1)%parts.length)}>Explore {parts[(selected+1)%parts.length].name.toLowerCase()}<ChevronRight size={18}/></button></aside></section>
 <section className="structure-nav"><div className="nav-heading"><h2>Explore the parts</h2><span><MousePointer2 size={14}/> Click the model or select a structure</span></div><div className="parts">{parts.map((part,i)=><button key={part.name} aria-pressed={selected===i} onClick={()=>setSelected(i)} className={selected===i?'active':''} style={{'--part-color':part.color} as React.CSSProperties}><span className="index">0{i+1}</span><i/>{part.name}</button>)}</div></section>
 <footer><span>Simplified teaching model · Colors distinguish structures · Not to scale</span><a href="https://www.ncbi.nlm.nih.gov/books/NBK11103/" target="_blank" rel="noreferrer">Read more: Neuroscience, NCBI <ArrowUpRight size={14}/></a></footer>
 </main>}
